// Blank Object
// {
//   id: "",
//   icon: "",
//   duration: "",
//   cooldown: "",
//   name: {
//     en: "",
//     de: "",
//     fr: "",
//     ru: "",
//     ch: "",
//   },
//   cooldownText: {
//     en: "",
//     de: "",
//     fr: "",
//     ru: "",
//     ch: "",
//   },
//   effectText: {
//     en: "",
//     de: "",
//     fr: "",
//     ru: "",
//     ch: "",
//   },
// },

export const classAbilityDB = [
  /* ---------------------------------------------------------------------------------------------- */
  /*                                             Paladin                                            */
  /* ---------------------------------------------------------------------------------------------- */
  /* --------------------------------------- Avenging Wrath --------------------------------------- */
  // https://www.wowhead.com/spell=31884/avenging-wrath
  {
    id: 31884,
    icon: "spell_holy_avenginewrath",
    duration: 20,
    cooldown: 120,
    name: {
      en: "Avenging Wrath",
      de: "Zornige Vergeltung",
      fr: "Courroux vengeur",
      ru: "Гнев карателя",
      ch: "复仇之怒",
    },
    cooldownText: {
      en: "2 min cooldown",
      de: "2 min Abklingzeit",
      fr: "2 min de recharge",
      ru: "Восстановление: 2 мин",
      ch: "2​分钟 冷却",
    },
    effectText: {
      en: "Call upon the Light to become an avatar of retribution, increasing your damage, healing, and critical strike chance by 20% for 20 sec.",
      de: "Ruft das Licht an, um für 20 sec zu einem Avatar der Vergeltung zu werden. Erhöht Euren Schaden, Eure Heilung und Eure kritische Trefferchance um 20%.",
      fr: "Vous faites appel au pouvoir de la Lumière pour devenir un avatar de vindicte, ce qui augmente vos dégâts, vos soins et vos chances de coup critique de 20% pendant 20 sec.",
      ru: "Вы взываете к Свету, становясь аватарой воздаяния. Увеличивает урон и силу исцеления, а также повышает вероятность критического удара на 20% на 20 sec.",
      ch: "召唤圣光之力，成为惩戒的化身。你的伤害、治疗效果及爆击几率提高20%，持续20 sec。",
    },
  },

  /* ---------------------------------------- Aura Mastery ---------------------------------------- */
  // https://www.wowhead.com/spell=31821/aura-mastery
  {
    id: 31821,
    icon: "spell_holy_auramastery",
    duration: 8,
    cooldown: 180,
    name: {
      en: "Aura Mastery",
      de: "Aurenmeisterschaft",
      fr: "Maîtrise des auras",
      ru: "Владение аурами",
      ch: "光环掌握",
    },
    cooldownText: {
      en: "3 min cooldown",
      de: "3 min Abklingzeit",
      fr: "3 min de recharge",
      ru: "Восстановление: 3 мин",
      ch: "3​分钟 冷却",
    },
    effectText: {
      en: "Empowers your chosen aura for 8 sec.",
      de: "Verstärkt Eure gewählte Aura für 8 sec",
      fr: "Renforce l’aura choisie pendant 8 sec.",
      ru: "Повышает эффективность выбранной ауры на 8 sec.",
      ch: "强化你选择的光环，持续8 sec。",
    },
  },

  /* ----------------------------------- Blessing of Protection ----------------------------------- */
  // https://www.wowhead.com/spell=1022/blessing-of-protection
  {
    id: 1022,
    icon: "spell_holy_sealofprotection",
    duration: 10,
    cooldown: 300,
    name: {
      en: "Blessing of Protection",
      de: "Segen des Schutzes",
      fr: "Bénédiction de protection",
      ru: "Благословение защиты",
      ch: "保护祝福",
    },
    cooldownText: {
      en: "5 min recharge",
      de: "5 min Wiederaufladung",
      fr: "5 min de recharge",
      ru: "Время восстановления 5 мин",
      ch: "5​分钟 充能",
    },
    effectText: {
      en: "Blesses a party or raid member, granting immunity to Physical damage and harmful effects for 10 sec. Cannot be used on a target with Forbearance. Causes Forbearance for 30 sec.",
      de:
        "Segnet ein Gruppen- oder Schlachtzugsmitglied und gewährt ihm 10 sec lang Immunität gegen körperlichen Schaden und schädliche Effekte. Kann nicht auf Ziele gewirkt werden, die von 'Vorahnung' betroffen sind. Ruft den Effekt 'Vorahnung' hervor, der 30 sec lang anhält.",
      fr:
        "Vous bénissez un membre du groupe ou raid, ce qui le protège des dégâts physiques et des effets néfastes pendant 10 sec. Ne peut être utilisé sur une cible affectée par Longanimité. Entraîne Longanimité pendant 30 sec.",
      ru:
        "Вы благословляете участника группы или рейда, делая его невосприимчивым к физическому урону и отрицательным эффектам на 10 sec. Невозможно применить к цели, находящейся под действием 'Воздержанности'. Вызывает 'Воздержанность' на 30 sec.",
      ch: "祝福一名小队或团队成员，使其免疫所有物理攻击和有害效果，持续10 sec。 无法对有自律效果的目标使用。造成自律，持续30 sec。",
    },
  },

  /* ------------------------------------- Blessing of Freedom ------------------------------------ */
  // https://www.wowhead.com/spell=1044/blessing-of-freedom
  {
    id: 1044,
    icon: "spell_holy_sealofvalor",
    duration: 8,
    cooldown: 25,
    name: {
      en: "Blessing of Freedom",
      de: "Segen der Freiheit",
      fr: "Bénédiction de liberté",
      ru: "Благословенная свобода",
      ch: "自由祝福",
    },
    cooldownText: {
      en: "25 sec recharge",
      de: "25 sek. Wiederaufladung",
      fr: "25 s de recharge",
      ru: "Время восстановления 25 сек",
      ch: "25​秒 充能",
    },
    effectText: {
      en: "Blesses a party or raid member, granting immunity to movement impairing effects",
      de: "Segnet ein Gruppen- oder Schlachtzugsmitglied und gewährt ihm Immunität gegen bewegungseinschränkende Effekte.",
      fr: "Vous bénissez un membre du groupe ou raid, ce qui le rend insensible aux effets affectant le déplacement",
      ru: "Вы благословляете участника группы или рейда, делая его невосприимчивым к затрудняющим передвижение эффектам",
      ch: "祝福一名小队或团队成员，使其免疫任何移动限制效果，",
    },
  },
  /* ---------------------------------------- Lay on Hands ---------------------------------------- */
  // https://www.wowhead.com/spell=633/lay-on-hands
  {
    id: 633,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "Lay on Hands",
      de: "Handauflegung",
      fr: "Imposition des mains",
      ru: "Возложение рук",
      ch: "圣疗术",
    },
    cooldownText: {
      en: "10 min cooldown",
      de: "10 min Abklingzeit",
      fr: "10 min de recharge",
      ru: "Восстановление: 10 мин",
      ch: "10​分钟 冷却",
    },
    effectText: {
      en: "Heals a friendly target for an amount equal to your maximum health. Cannot be used on a target with Forbearance. Causes Forbearance for 30 sec.",
      de:
        "Heilt ein verbündetes Ziel um einen Betrag, der Eurer maximalen Gesundheit entspricht. Kann nicht auf Ziele gewirkt werden, die von 'Vorahnung' betroffen sind. Ruft den Effekt 'Vorahnung' hervor, der 30 sec lang anhält.",
      fr:
        "Rend à une cible alliée un montant de points de vie égal à votre maximum de points de vie. Ne peut être utilisé sur une cible affectée par Longanimité. Entraîne Longanimité pendant 30 sec.",
      ru: "Восполняет союзнику здоровье в объеме, равном вашему максимальному запасу здоровья. Не действует на цели с 'Воздержанностью'. Вызывает 'Воздержанность' на 30 sec.",
      ch: "治疗一个友方目标，数值相当于你的最大生命值。 无法对有自律效果的目标使用。造成自律效果，持续30 sec。",
    },
  },

  /* ----------------------------------------- Divine Toll ---------------------------------------- */
  // https://www.wowhead.com/spell=304971/divine-toll
  {
    id: 304971,
    icon: "ability_bastion_paladin",
    duration: 0,
    cooldown: 60,
    covenant: "Kyrian",
    name: {
      en: "Divine Toll",
      de: "Göttlicher Glockenschlag",
      fr: "Glas divin",
      ru: "Божественный благовест",
      ch: "圣洁鸣钟",
    },
    cooldownText: {
      en: "1 min cooldown",
      de: "1 min Abklingzeit",
      fr: "1 min de recharge",
      ru: "Восстановление: 1 мин",
      ch: "1​分钟 冷却",
    },
    effectText: {
      en: "Instantly cast Holy Shock, Avenger's Shield, or Judgment on up to 5 targets within 30 yds (based on your current specialization).",
      de: "Setzt abhängig von Eurer Spezialisierung sofort 'Heiliger Schock', 'Schild des Rächers' oder 'Richturteil' gegen bis zu 5 Ziele innerhalb von 30 Metern ein.",
      fr: "Vous lancez instantanément Horion sacré, Bouclier du vengeur ou Jugement sur 5 cibles à moins de 30 mètres (en fonction de votre spécialisation actuelle).",
      ru: "Мгновенно применяет к 5 цели в радиусе 30 м 'Шок небес', 'Щит мстителя' или 'Правосудие' (в зависимости от вашей текущей специализации).",
      ch: "立即对30码范围内最多5个目标施放神圣震击、复仇者之盾或审判（基于你当前的职业专精）。",
    },
  },

  {
    id: 316958,
    icon: "ability_revendreth_paladin",
    duration: 30,
    cooldown: 240,
    covenant: "Venthyr",
    name: {
      en: "Ashen Hallow",
      de: "Ascheweihung",
      fr: "Bénédiction cendrée",
      ru: "Пепельное освящение",
      ch: "红烬圣土",
    },
    cooldownText: {
      en: "4 min cooldown",
      de: "4 min Abklingzeit",
      fr: "4 min de recharge",
      ru: "Восстановление: 4 мин",
      ch: "4​分钟 冷却",
    },
    effectText: {
      en:
        "Hallow the target area for 30 sec. Enemies in the area suffer up to [(55% of Spell power) * 30 / 2] Shadow damage, and allies are healed for up to [(42% of Spell power) * 30 / 2], reduced if there are more than 5 targets. Within the Hallow, you may use Hammer of Wrath on any target, and its damage is increased by 100%.",
      de:
        "Weiht den Zielbereich für 30 sec Gegner innerhalb des Bereichs erleiden bis zu [(55% of Spell power) * 30 / 2] Schattenschaden und Verbündete werden um bis zu [(42% of Spell power) * 30 / 2] Gesundheit geheilt. Die Werte verringern sich bei mehr als 5 Zielen. Innerhalb der Weihung könnt Ihr 'Hammer des Zorns' gegen jedes beliebige Ziel einsetzen und die Fähigkeit verursacht 100% mehr Schaden.",
      fr:
        "Vous bénissez la zone visée pendant 30 sec. Les ennemis qui s’y trouvent subissent [(55% of Spell power) * 30 / 2] points de dégâts d’Ombre et les alliés récupèrent [(42% of Spell power) * 30 / 2] points de vie, montant réduit si le nombre de cibles est supérieur à 5. Dans la zone d’effet de la bénédiction, vous pouvez utiliser Marteau de courroux sur n’importe quelle cible et ses dégâts sont augmentés de 100%.",
      ru:
        "Освящает указанную область на 30 sec. Противники в области получают до [(55% of Spell power) * 30 / 2] ед. урона от темной магии, а союзники в ней восполняют до [(42% of Spell power) * 30 / 2] ед. здоровья. Если целей более 5, эффективность снижается. Находясь в области действия, вы можете применять 'Молот гнева' к любой цели, а наносимый им урон увеличивается на 100%.",
      ch:
        "圣化目标区域，持续30 sec。区域内的敌人受到最多[(55% of Spell power) * 30 / 2]点暗影伤害，并为区域内的盟友恢复最多[(42% of Spell power) * 30 / 2]点生命值。目标多于5个时效果会衰减。 在圣化区域内，你可以对任何目标使用愤怒之锤，且愤怒之锤造成的伤害提高100%。",
    },
  },

  {
    id: 328204,
    icon: "ability_maldraxxus_paladin",
    duration: 0,
    cooldown: 30,
    covenant: "Necrolord",
    name: {
      en: "Vanquisher's Hammer",
      de: "Hammer des Bezwingers",
      fr: "Marteau du vainqueur",
      ru: "Молот покорителя",
      ch: "征服者之锤",
    },
    cooldownText: {
      en: "30 sec recharge",
      de: "30 sek. Wiederaufladung",
      fr: "30 s de recharge",
      ru: "Время восстановления 30 сек",
      ch: "30​秒 充能",
    },
    effectText: {
      en: "Throws a hammer at your target dealing (136% of Spell power) Shadow damage, and empowering your next Word of Glory to automatically trigger Light of Dawn. Generates 1 Holy Power.",
      de:
        "Wirft einen Hammer auf Euer Ziel, der (136% of Spell power) Schattenschaden verursacht und Euren nächsten Einsatz von 'Wort der Herrlichkeit' ermächtigt, sodass automatisch 'Licht der Morgendämmerung'. Erzeugt 1 Heilige Kraft.",
      fr:
        "Vous lancez sur votre cible un marteau qui inflige (136% of Spell power) points de dégâts d’Ombre et renforce le prochain Mot de gloire qui déclenche automatiquement Lumière de l’aube. Génère 1 points de puissance sacrée.",
      ru: "Бросает в цель молот, нанося (136% of Spell power) ед. урона от темной магии. Следующее 'Торжество' автоматически активирует 'Свет зари'. Дает 1 ед. энергии Света.",
      ch: "向你的目标投掷锤子并造成(136% of Spell power)点暗影伤害，使你的下一个 荣耀圣令自动触发黎明之光。 产生1点神圣能量。",
    },
  },

  {
    id: 328278,
    icon: "ability_ardenweald_paladin_autumn",
    duration: 30,
    cooldown: 45,
    name: {
      en: "Blessing of the Seasons",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 740,
    icon: "spell_nature_tranquility",
    duration: 8,
    cooldown: 180,
    name: {
      en: "Tranquility",
      de: "Gelassenheit",
      fr: "Tranquillité",
      ru: "Спокойствие",
      ch: "宁静",
    },
    cooldownText: {
      en: "3 min cooldown",
      de: "3 min Abklingzeit",
      fr: "3 min de recharge",
      ru: "Восстановление: 3 мин",
      ch: "3​分钟 冷却",
    },
    effectText: {
      en:
        "Heals all allies within 40 yards for [(59% of Spell power) * 5] over 8 sec. Each heal heals the target for another (6.88% of Spell power) over 8 sec, stacking. Healing increased by 100% when not in a raid.",
      de:
        "Heilt alle Verbündeten innerhalb von 40 Metern im Verlauf von 8 sec um [(59% of Spell power) * 5] Gesundheit. Jede Heilung heilt das Ziel zusätzlich im Verlauf von 8 sec um (6.88% of Spell power) Gesundheit. Dieser Effekt ist stapelbar. Die Heilung ist außerhalb eines Schlachtzugs um 100% erhöht.",
      fr:
        "Rend [(59% of Spell power) * 5] points de vie aux alliés à moins de 40 m en 8 sec. Tous les soins prodigués à la cible lui rendent aussi (6.88% of Spell power) points de vie en 8 sec. Effet cumulable. Soins augmentés de 100% si vous ne faites pas partie d’un raid.",
      ru:
        "Восполняет [(59% of Spell power) * 5] ед. здоровья за 8 sec союзникам в радиусе 40 м. Каждое исцеление восполняет цели еще (6.88% of Spell power) ед. здоровья за 8 sec. Эффект суммируется. Вне рейда исцеление усиливается на 100%.",
      ch: "在8 sec内为40码范围内的所有盟友恢复[(59% of Spell power) * 5]点生命值。每次治疗可为目标额外在8 sec内恢复(6.88% of Spell power)点生命值。此效果可叠加。 当你不在团队时，该治疗效果提高100%。",
    },
  },

  {
    id: 33891,
    icon: "ability_druid_improvedtreeform",
    duration: 30,
    cooldown: 180,
    name: {
      en: "Incarnation: Tree of Life",
      de: "Inkarnation: Baum des Lebens",
      fr: "Incarnation : Arbre de vie",
      ru: "Воплощение: древо жизни",
      ch: "化身：生命之树",
    },
    cooldownText: {
      en: "3 min cooldown",
      de: "3 min Abklingzeit",
      fr: "3 min de recharge",
      ru: "Восстановление: 3 мин",
      ch: "3​分钟 冷却",
    },
    effectText: {
      en:
        "Shapeshift into the Tree of Life, increasing healing done by 15%, increasing armor by 120%, and granting protection from Polymorph effects.  Functionality of Rejuvenation, Wild Growth, Regrowth, and Entangling Roots is enhanced. Lasts 30 sec. You may shapeshift in and out of this form for its duration.",
      de:
        "Verwandelt Euch in die Gestalt eines Baums des Lebens, wodurch Eure gewirkte Heilung um 15% und Eure Rüstung um 120% erhöht wird. Schützt Euch außerdem vor Verwandlungseffekten. Die Funktionalität Eurer Zauber 'Verjüngung', 'Wildwuchs', 'Nachwachsen' und 'Wucherwurzeln' wird verstärkt. Hält 30 sec lang an. Ihr könnt Euch während der Effektdauer beliebig in diese Gestalt und zurück verwandeln.",
      fr:
        "Vous vous transformez en arbre de vie, ce qui augmente les soins prodigués de 15% et l’armure de 120%, et vous protège des effets de métamorphose. Augmente l’efficacité de Récupération, Croissance sauvage, Rétablissement et Sarments. Dure 30 sec. Vous pouvez librement adopter cette forme et la quitter pendant toute sa durée.",
      ru:
        "Вы превращаетесь в древо жизни. В этом облике эффективность исцеления увеличивается на 15%, а броня усиливается на 120%; также вы становитесь невосприимчивы к эффектам превращения. Кроме того, усиливаются ваши заклинания 'Омоложение', 'Буйный рост', 'Восстановление' и 'Гнев деревьев'. Время действия – 30 sec. Вы можете принимать или сбрасывать этот облик в течение всего времени действия эффекта.",
      ch: "进入生命之树形态，治疗效果提高15%，护甲值提高120%，并免疫变形效果。得到强化的法术：回春术、野性成长、愈合和纠缠根须。 持续30 sec。你可以在持续期间在其他形态与生命之树之间切换。",
    },
  },

  {
    id: 197721,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 326434,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 323546,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 325727,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 323764,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 265202,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 64843,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 47788,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 62618,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 246287,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 109964,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 47536,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 33206,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 325013,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 323673,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },
  {
    id: 324724,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 327661,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 108280,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 98008,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },
  {
    id: 207399,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 324386,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 320674,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 326059,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 328923,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 115310,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 310454,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 326860,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 325216,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 327104,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 196718,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 97462,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 15286,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 51052,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 10060,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 102342,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 6940,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 116849,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },

  {
    id: 116841,
    icon: "",
    duration: "",
    cooldown: "",
    name: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    cooldownText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
    effectText: {
      en: "",
      de: "",
      fr: "",
      ru: "",
      ch: "",
    },
  },
];
